- Node.js/Sha256sumVerifier.py
- Node.js/node.verify.recipe
I noticed this alongside the v4.0.0 announcement. I opted to just switch all SHA1 to SHA256 as it's only used in this node recipe.
> Update node.verify for SHA256 verification

- GPGTools/GPGSuite.download.recipe
Overnight our build of the GPGSuite failed saying:
Processor: URLTextSearcher: Error: No match found on URL
This is because there has been a new release of the suite (GPG Suite
2016.07 July 4th, 2016 according to the release notes which has version number:
2016.07_v2
so the regular expression:
href=\"https://releases.gpgtools.org/GPG_Suite-([0-9a-z\.\-]+)\.dmg\"
was not matching (as it didn't include the underscore character).
This patch just adds the underscore character to the regular expression,
meaning the download now succeeds.
> Update regular expression for new version

- Versions/Versions.download.recipe
the latest version it will now download is for 10.12 and up, no longer for MacOS10.11.x
> update dev id

- MongoDB/MongoDB.pkg.recipe
The MongoDB pkg was installing Mongo into `/usr/local/mongodb` but wasn't doing anything else, thus leaving it in a fairly unusable state. 
This PR sets the pkg to resemble what you'd get following the default [install instructions](https://docs.mongodb.com/manual/tutorial/install-mongodb-on-os-x/) from MongoDB.
`/data/db` is created since that's the default path `mongod` looks for when it runs. `/etc/paths.d/mongodb` gets created with `/usr/local/mongodb/bin` as its contents so that the mongo db binary path gets added to `PATH`.
**Sample run:**
```
autopkg run MongoDB.pkg.recipe -v
Processing MongoDB.pkg.recipe...
WARNING: MongoDB.pkg.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher
URLTextSearcher: Found matching text (version): …
```
> [MongodDB.pkg] Add mongo to PATH and create /data/db

- Postbox/Postbox.download.recipe
- Versions/Versions.download.recipe
Using `expected_authority_names` for verifying .app bundles is not supported in AutoPkg 1.0.3.
> Replaced expected_authority_names with requirement string

- Jenkins/Jenkins.munki.recipe
Change the default uninstall_method from removepackages to uninstall_script 
https://wiki.jenkins.io/display/JENKINS/Thanks+for+using+OSX+Installer
I know the removepackages method leaves /Applications/Jenkins/ folder still intact, and perhaps some other remnants.
> Utilize uninstall_script

- Understand/Understand.pkg.recipe
- jq/jq.pkg.recipe
Because variables can be overridden, it's a good idea to make sure that the recipe will still work even if a non-default variables used. One issue that would prevent recipes from running is using a `NAME` variable in paths that should be hard-coded (e.g. `/Applications/Foo.app`).
This PR removes the `NAME` variable from all file paths and replaces it with the actual app name, which should make the recipe more resilient for overrides.
> Remove NAME variable from app paths

- GPGTools/GPGSuite.munki.recipe
Use the min os requirement from the sparkle feed rather than a hardcoded value.
> Use sparkle feed minimum_os_version

- Jenkins/JenkinsURLProvider.py
- Node.js/NodeLatestURLProvider.py
- SharedProcessors/EasyInstallPkgbuilder.py
- SharedProcessors/GPGSignatureVerifier.py
- SharedProcessors/PkgsrcUpdater.py
- SharedProcessors/PyPIInfoProvider.py
- SharedProcessors/SVNUpdater.py
- SharedProcessors/VersionFixer.py
In order to make your processors more compatible with AutoPkg running in Python 3, I've applied a few adjustments suggested by `python-modernize`, `pylint --py3k`, and `pylint` in general.
More adjustments may need to be made manually later, but this should catch the low-hanging fruit right now.
> Basic python3 compatibility

- Understand/Understand.download.recipe
Context: The [CodeSignatureVerifier](https://github.com/autopkg/autopkg/wiki/Using-CodeSignatureVerification) processor ensures that the downloaded applications/packages are signed by the expected developer certificate. Although this is not a guarantee that the payload is trouble-free, it's a good indicator that the file you downloaded is the one you intended to download.
> Add CodeSignatureVerifier processor

- SharedProcessors/GPGSignatureVerifier.py
I think commit #118 broke the signature verifier?!
Example:
```
>>> print s
[GNUPG:] NEWSIG
gpg: Signature made Sat Aug 24 23:52:23 2019 CEST
gpg:                using RSA key 8C31E5A17DD5D932B448FE1DE8A664480D9E43F5
[GNUPG:] KEY_CONSIDERED 85E38F69046B44C1EC9FB07B76D78F0500D026C4 0
[GNUPG:] SIG_ID TmBpEFp3cLGQ6E6jgjCZhMy0m0U 2019-08-24 1566683543
[GNUPG:] KEY_CONSIDERED 85E38F69046B44C1EC9FB07B76D78F0500D026C4 0
gpg: checking the trustdb
gpg: no ultimately trusted keys found
[GNUPG:] GOODSIG E8A664480D9E43F5 GPGTools Team <team@gpgtools.org>
gpg: Good signature from "GPGTools Team <team@gpgtools.org>" [unknown]
gpg:                 aka "[jpeg image of size 5871]" [unknown]
[GNUPG:] VALIDSIG 8C31E5A17DD5D932B448FE1DE8A664480D9E43F5 2019-08-24 1566683543 0 4 0 1 8 00 …
```
> Fix regression in re.search

- Jenkins/Jenkins.download.recipe
- Jenkins/JenkinsURLProvider.py
This PR updates JenkinsURLProvider to use the new [URLGetter superclass](https://github.com/autopkg/autopkg/wiki/Downloading-from-the-Internet-in-Custom-Processors), which adds compatibility with Python 3 and AutoPkg 2. It also uses LooseVersion to determine the latest available version of Jenkins, since their "latest" redirect appears to no longer work as of version 2.214.
AutoPkg verbose run logs:
https://gist.github.com/homebysix/a34f2f456277deb8ae5d61e165d22559
> Update JenkinsURLProvider with URLGetter, LooseVersion

- GPGTools/GPGSuite.download.recipe
GPGSuite recently changed their developer team name leading the download recipe to fail. 
Mon Jun  8 16:27:28 2020 b'' autopkg_tools: b'CodeSignatureVerifier: Signature is valid'
Mon Jun  8 16:27:28 2020 b'' autopkg_tools: b'CodeSignatureVerifier: Mismatch in authority names'
Mon Jun  8 16:27:28 2020 b'' autopkg_tools: b'CodeSignatureVerifier: Expected: Developer ID Installer: Lukas Pitschl (PKV8ZPD836) -> Developer ID Certification Authority -> Apple Root CA'
Mon Jun  8 16:27:28 2020 b'' autopkg_tools: b'CodeSignatureVerifier: Found:    Developer ID Installer: GPGTools GmbH (PKV8ZPD836) -> Developer ID Certification Authority -> Apple Root CA'
> Update GPGSuite team name

- ownCloud/ownCloudDesktopClient.download.recipe
The old URL (https://owncloud.org/download) now 404's and it looks like this page has been moved to https://owncloud.com/desktop-app/
> URL Change

- MySQL/MySQLCommunityServer.download.recipe
Detected and changed HTTPS URLs automatically using my [HTTPS Spotter](https://www.elliotjordan.com/posts/autopkg-https/) script, and then tested all changed recipes manually to ensure download success.
> Update all available URLs from HTTP to HTTPS

- Understand/Understand.download.recipe
The correct argument name for [CodeSignatureVerifier](https://github.com/autopkg/autopkg/wiki/Processor-CodeSignatureVerifier) is `requirement`.
> Adjust name of CodeSignatureVerifier argument

- MySQL/MySQLCommunityServer.download.recipe
- MySQL/MySQLCommunityServer.munki.recipe
Hi Gerard,
Oracle now offers two subversions of their .dmg. One for regular Intel Macs and one for ARM Macs.
By default the recipe now picks up ARM. This does not run on Intel Macs. That's why I'm adding architecture support.
I'm not entirely sure I should add the architecture to .munki.recipe too because that will restrict people from running x86_64 version of this app on arm64 laptops while that would work. Not the other way around though, for sure!
- please adjust my PR/MR if you want to remove that.
With regards to .download.recipe.
I've included some cut up output of running .download.recipe for both architectures.
**Test x86_64**
'ARCHITECTURE': 'x86_64'
'RELEASE': '8.0'
'Output': {'match': 'mysql-8.0.26-macos11-',
'rel_url': 'mysql-8.0.26-macos11-',
'version': '8.0.26'}
'url': …
> Add architecture support to MySQL Community Server

- Versions/Versions.download.recipe
The Sparkle feed URL has changed for Versions.app and the old URL does not seem to receive updates any more.
> Versions.app: Sparkle feed URL updated

- ownCloud/ownCloudDesktopClient.download.recipe
The download url for owncloud currently has a double slash in it. 
Added support for this with the addition of a quantifier to the regex.
> Added ownclouds error in their current url to regex

- DotNet/DotNetSDK.download.recipe
- changed default `RELEASE` to "LTS" ("Current" is no longer a valid option and causes `DotNetURLProvider` to return error `Unable to parse .DotNet release.`)
- added platform architecture selection support (`PLATFORM_ARCH` input variable can be set to `arm64` or `x64`)
- changed downloaded filename to reflect platform architecture and version
> changed default RELEASE to LTS, added platform architecture selection

- SharedProcessors/GPGSignatureVerifier.py
- SharedProcessors/PyPIInfoProvider.py
As of macOS Monterey 12.3, the version of Python 2 that shipped with macOS located at `/usr/bin/python` [has been removed](https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes). More context can be found in some posts from Mac admins at the beginning of 2022, aggregated [here](https://scriptingosx.com/2022/03/macos-monterey-12-3-removes-python-2-link-collection/).
Since [version 2.0.2](https://github.com/autopkg/autopkg/releases/tag/v2.0.2), AutoPkg's installer has included its own Python 3 framework, symlinked from `/usr/local/autopkg/python`. This pull request adjusts the "shebang" interpreter paths of processors to replace `/usr/bin/env python` with the AutoPkg Python 3 path.
NOTE: Because AutoPkg processors are imported as modules by AutoPkg and not …
> Update Python path in processors to reflect changes in macOS 12.3+

- jq/jq.pkg.recipe
Currently the jq PKG is rebuilt on every run of autopkg. This can be avoided by setting a predicate to stop the build if the download step does not download a new binary. 
The original behavior could be maintained if the BUILD_PREDICATE input variable is set to FALSEPREDICATE  in an override. This would always evaluate to False and thereby bypass the StopProcessingIf processor.
> Skip building jq package when there is no change

- Enpass/Enpass.download.recipe
Dropped URLTextSearcher and modified URLDownloader
Fixes #246
> Fix for enpass.download-recipe

- Crystal/Crystal.download.recipe
This PR updates the asset regex pattern used by Crystal.download.
Verbose recipe run output:
```
% autopkg run -vvq 'Crystal/Crystal.download.recipe'
Processing Crystal/Crystal.download.recipe...
WARNING: Crystal/Crystal.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
GitHubReleasesInfoProvider
{'Input': {'asset_regex': 'crystal-[0-9\\.\\-]+\\.universal\\.pkg',
'github_repo': 'crystal-lang/crystal'}}
GitHubReleasesInfoProvider: No value supplied for CURL_PATH, setting default value of: /usr/bin/curl
GitHubReleasesInfoProvider: No value supplied for GITHUB_URL, setting default value of: https://api.github.com
GitHubReleasesInfoProvider: No value supplied for GITHUB_TOKEN_PATH, setting default value of: ~/.autopkg_gh_token …
```
> Fix Crystal recipes

- MongoDB/MongoDB.download.recipe
- MongoDB/MongoDB.munki.recipe
- MongoDB/MongoDB.pkg.recipe
This PR updates the pattern used to download the Mac version of MongoDB. It also adds an input variable that can be used to specify which architecture to download.
Verbose recipe run with default Intel architecture:
```
% autopkg run -vvq 'MongoDB/MongoDB.download.recipe'
Processing MongoDB/MongoDB.download.recipe...
WARNING: MongoDB/MongoDB.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher
{'Input': {'re_pattern': '"(https://fastdl.mongodb.org/osx/mongodb-macos-x86_64-(?P<version>[\\d\\.]+)\\.tgz)"',
'result_output_var_name': 'url',
'url': 'https://www.mongodb.com/try/download/community-edition/releases'}}
URLTextSearcher: Found matching text (version): 8.0.4
URLTextSearcher: Found matching text (url): …
```
> Fix MongoDB recipes and add ARCH input variable

- Puppet/PDK.download.recipe
This PR updates the default OS version for PDK downloads (10.12 is no longer available), and adds an ARCH input variable for specifying whether to download the Intel or Apple Silicon version of PDK.
Verbose recipe run output:
```
% autopkg run -vvq 'Puppet/PDK.download.recipe'
Processing Puppet/PDK.download.recipe...
WARNING: Puppet/PDK.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLDownloader
{'Input': {'filename': 'PDK.dmg',
'url': 'https://pm.puppet.com/cgi-bin/pdk_download.cgi?dist=osx&rel=13&arch=x86_64&ver=latest'}}
URLDownloader: No value supplied for prefetch_filename, setting default value of: False
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
URLDownloader: Storing new …
```
> Fix PDK recipes and add ARCH input variable

- Understand/Understand.download.recipe
- Understand/Understand.munki.recipe
- Understand/Understand.pkg.recipe
This PR adjusts the Understand recipes to leverage the new Universal dmg download.
Verbose recipe run output for the download, pkg, and munki recipes:
```
% autopkg run -vvq Understand/Understand.*.recipe
Processing Understand/Understand.download.recipe...
WARNING: Understand/Understand.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher
{'Input': {'re_pattern': '(https://latest.scitools.com/Understand/Understand-(?P<version>[\\d\\.]+)-macOS-Universal.dmg)',
'result_output_var_name': 'url',
'url': 'https://licensing.scitools.com/download/thanks/macOS-Universal.dmg'}}
URLTextSearcher: Found matching text (version): 7.0.1213
URLTextSearcher: Found matching text (url): https://latest.scitools.com/Understand/Understand-7.0.1213-ma …
```
> Fix Understand recipes

- YubiKey/YubiKeyAuthenticator.download.recipe
This PR adjusts the Yubikey Authenticator recipes to accept the new dmg download format.
Verbose recipe run output:
```
% autopkg run -vvq 'YubiKey/YubiKeyAuthenticator.download.recipe'
Processing YubiKey/YubiKeyAuthenticator.download.recipe...
WARNING: YubiKey/YubiKeyAuthenticator.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher
{'Input': {'re_pattern': 'href="yubico-authenticator-([\\d\\.]+)-mac.dmg"',
'result_output_var_name': 'version',
'url': 'https://developers.yubico.com/yubioath-flutter/Releases/'}}
URLTextSearcher: Found matching text (version): 7.1.1
{'Output': {'version': '7.1.1'}}
URLDownloader
{'Input': {'filename': 'YubiKeyAuthenticator-7.1.1.dmg',
'url': …
```
> Fix Yubikey Authenticator recipes

- 1Password/1PasswordCLI.download.recipe
The 1Password CLI recipes in this repo are downloading version 1 of the tool, and are not functionally different than the recipes in apettinen-recipes that download the newer version 2 of the tool.
This PR deprecates the 1Password CLI recipes and points users to their equivalents in the apettinen-recipes repo.
> Deprecate 1Password CLI recipes

- YubiKey/YubiKeyAuthenticator.jss.recipe
[JSSImporter](https://github.com/jssimporter/JSSImporter) is no longer maintained. This pull request marks JSS type recipes as deprecated, and urges users to consider switching to equivalent [JamfUploader](https://github.com/grahampugh/jamf-upload/wiki/JamfUploader-AutoPkg-Processors) recipes.
Thanks for considering!
_This PR was submitted using [Repo Lasso](https://github.com/homebysix/repo-lasso) v1.2.0._
> Deprecate JSS recipes

- MongoDB/MongoDB.munki.recipe
We're seeing errors with the latest change to the MongoDB.munki.recipe:
```
com.github.autopkg.gerardkok-recipes/MongoDB/MongoDB.munki.recipe: unexpected key at line 36
```
> Fix MongoDB.munki.recipe

- MySQL/MySQLCommunityServer-Universal.download.recipe
- MySQL/MySQLCommunityServer.download.recipe
Use a more recent user-agent when searching for the download url, but unset the user agent when downloading, otherwise we get a 403.
> more recent user-agent, but unset it for downloading
